#git pull&&python tools/test.py configs/htc/htc_x101_32x4d_fpn_20e_16gpu_ridge3_with_preprocess.py /data1/qilei_chen/DATA/ROP_DATASET/mmdetection_work_dirs/htc_x101_32x4d_fpn_20e_ridge3_with_preprocess/epoch_20.pth --out /data1/qilei_chen/DATA/ROP_DATASET/9LESIONS/mmdetection_work_dirs/htc_x101_32x4d_fpn_20e_ridge3_with_preprocess/results.pkl --eval bbox segm --savedir /data1/qilei_chen/DATA/ROP_DATASET/9LESIONS/mmdetection_work_dirs/htc_x101_32x4d_fpn_20e_ridge3_with_preprocess/results_show --show
#git pull&&python tools/test.py configs/htc/htc_x101_32x4d_fpn_20e_16gpu_ridge3.py /data1/qilei_chen/DATA/ROP_DATASET/mmdetection_work_dirs/htc_x101_32x4d_fpn_20e_ridge3/epoch_40.pth --out /data1/qilei_chen/DATA/ROP_DATASET/9LESIONS/mmdetection_work_dirs/htc_x101_32x4d_fpn_20e_ridge3/results.pkl --eval bbox segm --savedir /data1/qilei_chen/DATA/ROP_DATASET/9LESIONS/mmdetection_work_dirs/htc_x101_32x4d_fpn_20e_ridge3/results_show --show

#git pull&&python tools/test.py configs/coco_volcanoes/faster_rcnn_x101_32x4d_fpn_1x_coco_volcanoes.py /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/faster_rcnn_x101_32x4d_fpn_1x_coco_volcanoes/latest.pth --out /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/faster_rcnn_x101_32x4d_fpn_1x_coco_volcanoes_results_show/results.pkl --eval bbox --savedir /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/faster_rcnn_x101_32x4d_fpn_1x_coco_volcanoes_results_show --show

#git pull&&python tools/test.py configs/coco_volcanoes/ssd512_coco_volcanoes.py /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/ssd512_coco_volcanoes/epoch_15.pth --out /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/ssd512_coco_volcanoes_results_show/results.pkl --eval bbox --savedir /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/ssd512_coco_volcanoes_results_show --show

#git pull&&python tools/test.py configs/coco_volcanoes/faster_rcnn_x101_32x4d_fpn_1x_coco_volcanoes_aug.py /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/faster_rcnn_x101_32x4d_fpn_1x_coco_volcanoes_aug/latest.pth --out /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/faster_rcnn_x101_32x4d_fpn_1x_coco_volcanoes_aug_results_show/results.pkl --eval bbox --savedir /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/faster_rcnn_x101_32x4d_fpn_1x_coco_volcanoes_aug_results_show --show

git pull&&python tools/test.py configs/coco_volcanoes/ssd512_coco_volcanoes_aug.py /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/ssd512_coco_volcanoes_aug/epoch_40.pth --out /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/ssd512_coco_volcanoes_aug_results_show/results.pkl --eval bbox --savedir /data1/qilei_chen/DATA/coco_volcanoes/work_dirs/ssd512_coco_volcanoes_aug_results_show --show